# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: cmake ktm test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        build_type: [Release]
        c_compiler: [gcc, clang, cl]
        include:
          - os: macos-latest
            c_compiler: clang
            cpp_compiler: clang++
            cmake_project: Xcode
            root: sudo
          - os: macos-latest
            c_compiler: gcc
            cpp_compiler: g++
            cmake_project: Unix\ Makefiles
            root: sudo
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
            cmake_project: Visual` Studio` 17` 2022
          - os: windows-latest
            c_compiler: gcc
            cpp_compiler: g++
            cmake_project: Unix` Makefiles 
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
            cmake_project: Unix\ Makefiles
            root: sudo
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
            cmake_project: Unix\ Makefiles
            root: sudo
        exclude:
          - os: macos-latest
            c_compiler: cl
          - os: windows-latest
            c_compiler: clang
          - os: ubuntu-latest
            c_compiler: cl

    steps:
    - uses: actions/checkout@v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Set reusable strings
      id: strings
      run: |
        echo "build_output_dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
        echo "build_output_test_dir=${{ github.workspace }}/build/test" >> "$GITHUB_OUTPUT" 

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build_output_dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DKTM_BUILD_TESTING=ON
        -S ${{ github.workspace }}
        -G ${{ matrix.cmake_project }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build_output_dir }} --config ${{ matrix.build_type }}

    - name: Test
      working-directory: ${{ steps.strings.outputs.build_output_test_dir }}
      run: ctest --build-config ${{ matrix.build_type }}

    - name: Install
      run: ${{ matrix.root }} cmake --install ${{ steps.strings.outputs.build_output_dir }} --config ${{ matrix.build_type }}